site_name: FViewer Documentation
site_url: https://heasarc.github.io/fviewer/
theme:
  name: material
  custom_dir: overrides/
  logo: app/fviewer-logo.svg
  favicon: app/fviewer-logo.svg
  # palette:
  #   scheme: slate
nav:
  - Getting Started: index.md
  - Demo: demo.md
  - The Workspace: workspace.md
  - Regions and Catalogs: regions-catalogs.md
  - Python interactions: python-api.md
  - Architecture & Contributing: architecture.md
  - API Reference: 
      - Core Client: api-core.md
      - Client Plugins: api-plugins.md

extra:
  announcement: |
    <b>Warning:</b> FViewer is in beta. Features may change.
    Please report <a href="https://github.com/heasarc/fviewer/issues">issues</a>.

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [./fviewer/]
          options:
            docstring_style: google # Or 'numpy' or 'sphinx'
            show_root_heading: true
            show_source: true